language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: 1
    secure: QaZkVbMOV0LRWx9EeDX4r2FBsFkWSRDjcqBPznZsQ5lrq5sd43Wbr3kIl1bjzzr7cwOaTnOZG4M8RY6DiIF24l4VzuV4n03OSeGk7YK32riOGq++4FCK2eLRdvmHEkhjploXV4XFVeb+jj9AtPzG27K0GSjiQ7XejEuvDUeYVbmPEA+ePIEBUMmwcIn5dbbqHkezwrp98DdBNGpMZtH0f3Z2PMan0jhZGgfBEE/KfeZPSrRvywNmuEqwGlFQSNj4rdH72/ik5Bz7z3missC1NPmmy0act5fV71jQIE7TviCulVcuaAbg6JuLlypN/Ir8YNJhW4r7ubMKCpTIhZEtu/ygYw2Yt8nmRnBNahpcQFTj7ol7//vJdGUb1Olh6oWTUAQKvR2BolqHy1gxUu+moRc5LrDs2nizuh6slOK62wxlRLObsCoE5fLar1d8mTef4y/Gx+8uM88k6TADb9eZ86GSmNl5bjC5M4Sg8rgbAAubPgVxbqtQwrep4pAWef7QDeH6Vr/2OWjKLEWzKlm7ostvNDdO5fu+eTDXUbZoGcITnFb6QVMp5jCQmhAj6BGqD8BJC77cGXS9tmQSpLjwe6zkNjFAQtnPIX3OJJPv26VUby79AoprsanGUz7dTSHUZWGzjMQWxgAqCWk8caeJh+wmGAvfloOsXaGgzgJKtcI=
  app: agile-headland-68712
  on:
    repo: Mrjustinfry/node-shopping-list-integration-tests
